substitutions:
  name: "ev-charge"
  friendly_name: ev-charge

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # min_version: 2024.6.0
  # name_add_mac_suffix: false
  # project:
  #   name: esphome.web
  #   version: dev

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "enter your encryption key"

  actions:
    - action: set_total
      variables:
        new_total: int
      then:
      - pulse_meter.set_total_pulses:
          id: sensor_ev_pulse_meter
          value: !lambda 'return new_total * 1000;'

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
#improv_serial:

wifi:
  # # use multi wifi networks
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # - ssid: !secret wifi_ssid2
  #   password: !secret wifi_password2

#  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
#captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# To have a "next url" for improv serial
#web_server:

# EV Power meter configuration entry
sensor:
  - platform: pulse_meter
    name: "EV Charge Power"
    id: sensor_ev_pulse_meter # Optional ID, necessary if you want to calculate the total daily energy
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    accuracy_decimals: 0
    pin: GPIO3

    filters:
      - multiply: 60 # (60s / impulse constant) * (1000W / 1kW)
      - throttle: 10s
      - filter_out: NaN

    internal_filter: 200ms
    timeout: 1min

    total:
      name: "EV Charge Total Energy"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 3
      filters:
        - multiply: 0.001  # (1/1000 pulses per kWh)

# DomBusEVSE proxy module
  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVCharging
    id: evse2270000
    register_type: holding
    address: 0
    unit_of_measurement: ""
    value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   name: EVRL2
  #   id: evse2270001
  #   register_type: holding
  #   address: 1
  #   unit_of_measurement: ""
  #   value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVInAC
    id: evse2270002
    register_type: holding
    address: 2
    unit_of_measurement: ""
    value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   name: EVMode
  #   id: evse2270003
  #   register_type: holding
  #   address: 3
  #   unit_of_measurement: ""
  #   value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVState
    id: evse2270004
    register_type: holding
    address: 4
    unit_of_measurement: ""
    value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   name: EVCurrent
  #   id: evse2270005
  #   register_type: holding
  #   address: 5
  #   unit_of_measurement: "A"
  #   value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVPower
    id: evse2270006
    register_type: holding
    address: 6
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVPowerSolar
    id: evse2270007
    register_type: holding
    address: 7
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVPowerGrid
    id: evse2270008
    register_type: holding
    address: 8
    unit_of_measurement: "W"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVVoltage
    id: evse2270009
    register_type: holding
    address: 9
    device_class: voltage
    unit_of_measurement: "V"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVPF
    id: evse2270010
    register_type: holding
    address: 10
    unit_of_measurement: "%"
    value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   name: EVRL2
  #   id: evse2270011
  #   register_type: holding
  #   address: 11
  #   unit_of_measurement: ""
  #   value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   name: EV3PSELECT
  #   id: evse2270513
  #   register_type: holding
  #   address: 513
  #   unit_of_measurement: ""
  #   value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   id: evse2279002
  #   name: EVMAXPOWER
  #   address: 9002
  #   register_type: holding
  #   value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   id: evse2279003
  #   name: EVSTARTPOWER
  #   address: 9003
  #   register_type: holding
  #   value_type: U_WORD


    #    address: 0x232B
    #    register_type: "read"
    ## reimplement using custom_command
    # 0x2 : modbus device address
    # 0x4 : modbus function code
    # 0x1 : high byte of modbus register address
    # 0x56: low byte of modbus register address
    # 0x00: high byte of total number of registers requested
    # 0x02: low byte of total number of registers requested


  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   id: evse2278192
  #   name: EVSE Slave Address
  #   custom_command: [ 0xE3, 0x03, 0x20, 0x00, 0x00, 0x01]
  #   value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   id: evse2278193
  #   name: EVSE Serial bitrate
  #   custom_command: [ 0xE3, 0x03, 0x20, 0x01, 0x00, 0x01]
  #   value_type: U_WORD

  # - platform: modbus_controller
  #   modbus_controller_id: modbus_evse
  #   id: evse2278194
  #   name: EVSE Serial parity
  #   custom_command: [ 0xE3, 0x03, 0x20, 0x02, 0x00, 0x01]
  #   value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279001
    name: EVMAXCURRENT
    custom_command: [ 0xE3, 0x4, 0x23, 0x29, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279002
    name: EVMAXPOWER
    custom_command: [ 0xE3, 0x4, 0x23, 0x2A, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279003
    name: EVSTARTPOWER
    custom_command: [ 0xE3, 0x4, 0x23, 0x2B, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279004
    name: EVSTOPTIME
    custom_command: [ 0xE3, 0x4, 0x23, 0x2C, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279005
    name: EVAUTOSTART
    custom_command: [ 0xE3, 0x4, 0x23, 0x2D, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279006
    name: EVMAXPOWER2
    custom_command: [ 0xE3, 0x4, 0x23, 0x2E, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279007
    name: EVMAXPOWERTIME
    custom_command: [ 0xE3, 0x4, 0x23, 0x2F, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279008
    name: EVMAXPOWERTIME2
    custom_command: [ 0xE3, 0x4, 0x23, 0x30, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279009
    name: EVWAITTIME
    custom_command: [ 0xE3, 0x4, 0x23, 0x31, 0x00, 0x01]
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279010
    name: EVMETERTYPE
    custom_command: [ 0xE3, 0x4, 0x23, 0x32, 0x00, 0x01]
    value_type: U_WORD

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2278198
    name: EVSE Revision major
    address: 8198
    register_type: read

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2278199
    name: EVSE Revision minor
    address: 8199
    register_type: read

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVRL2
    id: evse2270001
    register_type: holding
    address: 1
    unit_of_measurement: ""
    value_type: U_WORD
    min_value: 0
    max_value: 1
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVMode
    id: evse2270003
    register_type: holding
    address: 3
    unit_of_measurement: ""
    value_type: U_WORD
    min_value: 0
    max_value: 6
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EVCurrent
    id: evse2270005
    register_type: holding
    address: 5
    unit_of_measurement: "A"
    value_type: U_WORD
    min_value: 0
    max_value: 32
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2270011
    name: Grid Power
    address: 11
    register_type: holding
    value_type: U_WORD
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    name: EV3PSELECT
    id: evse2270513
    register_type: holding
    address: 513
    value_type: U_WORD
    min_value: 0
    max_value: 254
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279001n
    name: EVMAXCURRENTn
    address: 9001
    register_type: holding
    value_type: U_WORD
    min_value: 6
    max_value: 36
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279002n
    name: EVMAXPOWERn
    address: 9002
    register_type: holding
    value_type: U_WORD
    min_value: 1000
    max_value: 25000
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279003n
    name: EVSTARTPOWERn
    address: 9003
    register_type: holding
    value_type: U_WORD
    min_value: 800
    max_value: 25000
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279004n
    name: EVSTOPTIMEn
    address: 9004
    register_type: holding
    value_type: U_WORD
    min_value: 5
    max_value: 600
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279005n
    name: EVAUTOSTARTn
    address: 9005
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279006n
    name: EVMAXPOWER2n
    address: 9006
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 25000
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279007n
    name: EVMAXPOWERTIMEn
    address: 9007
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 43200
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279008n
    name: EVMAXPOWERTIME2n
    address: 9008
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 43200
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279009n
    name: EVWAITTIMEn
    address: 9009
    register_type: holding
    value_type: U_WORD
    min_value: 3
    max_value: 60
    internal: False
    use_write_multiple: False

  - platform: modbus_controller
    modbus_controller_id: modbus_evse
    id: evse2279010n
    name: EVMETERTYPEn
    address: 9010
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    internal: False
    use_write_multiple: False

# Restart configuration entry
switch:
  - platform: restart
    name: "EV Charge Restart"

# XIAO ESP32C3 configuration entry
uart:
  - id: uart_modbus_client
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 115200

modbus:
  - uart_id: uart_modbus_client
    id: modbus_client
    role: client

modbus_controller:
  - id: modbus_evse
    modbus_id: modbus_client
    address: 0xE3
    update_interval: 5s
